#redis
spring.redis.database=1
spring.redis.port=6379
spring.redis.host=118.31.2.9
#mysql--localhost
#spring.datasource.url=jdbc:mysql://118.31.2.9:3306/api-center
spring.datasource.url=jdbc:mysql://118.31.2.9:3306/pndb
spring.datasource.password=123456
spring.datasource.username=pndb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#web
server.port=9999
#mybatis-plus
mybatis-plus.configuration.map-underscore-to-camel-case=false
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.logic-delete-field=isDelete
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis.mapper-locations=classpath:mapper/*.xml
#swagger
swagger.enable=true
swagger.application-description=Programming-Navigation
swagger.application-version=1.0.x
swagger.application-name=Programming-Navigation
#knife4j
knife4j.enable=true
knife4j.openapi.description="Programming-Navigation"
knife4j.openapi.title=Programming-Navigation
knife4j.openapi.email=Programming-Navigation
knife4j.openapi.concat=Programming-Navigation
#gitee
gitee.client_id=d03f9cf389b1c0f79650902e9292344ae7fc864d57a215ec0604cee5fb4b7e3c
gitee.client_secret=0eec2d52e30222e54f325c68a596af5dd546dce96ccfb1b1d31bd1c6f90b0648
gitee.callback_url=http://127.0.0.1:9999/v1/usercenter/server/user/callback/login/gitee
#github
github.client_id=Ov23lio6psXvDkmBN0vz
github.client_secret=dfa294fbef65406173e848ef6f91d26352d037e6
github.callback_url=http://127.0.0.1:9999/v1/usercenter/server/user/callback/login/github
#gitlab
gitlab.client_id=580f3ebf3fb91369700ce5012ae87ec181c3b5004b7ae67ec28005ccee5b75b8
gitlab.client_secret=gloas-bbedb4d55d626073717eb13d8d60ffa6b500f14b096950e4cfcfe5d0c12e4bbf
gitlab.callback_url=http://127.0.0.1:9999/v1/usercenter/server/user/callback/login/gitlab
#file-set
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
file.access=jpg,png,pdf,md,word
#minio
minio.endpoint=121.40.157.239
minio.port=9001
minio.access-key=sllh
minio.secret-key=adminsllh
minio.bucketName=sllh

#alipay
alipay.appid=9021000143693037
alipay.appPrivateKey=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCAGM6i3t6X3UZhvl7e4p2GdLJWVP1kV43YxAFzWFcvAdW9MBHrCno5CqdnD0bYSd0bYvOBg93vvInX36KDIHxglYPsUaTB2Vn99UcCfJi2O59+J23osjxSqfzdwOlpQIOOkkUpmzDCJHh1KFJliN0FRyjXxL3ySWQhOVHzxro1U5XGaqd+ms7jsDMYTA3c79v/54Z+dvBMZMKjp7wVfLkGIWGYBNIq34TC33W8RGwJUjA8wn+nxvXLb05GDqWg+FTBiWqwdwy5XKxqatgDaT7IK/kP1BT5iC3maSKEmIlFVMFaMNKRpBZL/p3KsSSPi5NbKAkNwzCKPSboLiPRtRClAgMBAAECggEAE4Mz3s1yPNHhCbyU+QCuHDAkhlAV9TX9Dnr0+ZwIU8nExDfRUutaqNu9mk5SbVn7C1PsYdszcHRYzwBq4eyN5ayA1vuszDaOpce6FF/kZ0X3yqC49kxIMhNgyGq9Y2IHaC1Ryb+xErG5g6crvfm2KTqotw1qHcEeNo1jtW2dKcglavuzIM9Rhp6HcYy0zjMXJRvVv75ttVPHXsffjTHxSlgaef5y2ZerdhzmiROf7SkIfw9PrnmhJ1Qh+NKax2AFpWQVOWgDD0o7BDnoH/v2cVAaUBmI3nfL40ywmtIujrISIsXpzI2i5DK6CSwua0tz4fPn4T5kr03PpKSSVQpJFQKBgQDBgXp1zYtD4/BwEndYO/c1q5DsG1MO4mkCR6fHEpON/0MGpSWgCCvC9V6eX9Gr8WrX4Uq9tBvmOeXuW0Kuc4hA9bhh7f5DCmgsfqHQnJa464zHX+OBmTMAdel7zQjJH69jFGSNP9C+y/NK33ekPVC53Opvn87xnnC1BK7kMGtYYwKBgQCpd4Eg/A6IxQYZv1UzT3qGk9ulS+2bacqZszusJ/qRT9CDJ8bJgjYTj2Kd0Ua+8eaizFsYP30DslPSuYVGwAWNpNhgzqV/kNEAR/nYZlU3pEtmggQXXSLHWY72gb24RxGw7QtQTwt9Z9iyi+BMM4Mb0p0MkL7U/sMcqdGxf18NVwKBgDoKJPn6ib/2OWLUFxnO+qoNaK140KPRQx/c8DTknH9lxevTUwK6EK4sPJISOWhyQ9K2j11xDUEzsoSYuNpsarzZNtGgubfQAkj+Pni8zvRuKk6Os0Vm9wY3V627ZNw2dbupHTPEpU7lC3c0qcUIYxMscODENSUBmdqhqfdlknzzAoGAaX8Jld0TtzTf7Vtc0Mpjfi/Bho9T5XHgO/qF5VAl/hvvtBYo+/zhaR/TxmcnYWr5ptMMynWLf6ed4wq22ypiyqCaSvmZsWYXldM4x+w8lJzki3XY0iqaofswsmhmELe9XaTTbDUo8/KXxd6pzQYsUj+0oMPi6HmIQOm+rn6aT5UCgYAoeqhqWTHI3/nVQWF5urP0QJxdw7pN52mo4D47aLJ99HQsVL2dfPvOjuNu7f6PiVwxmKcsNH+/E9onNl/YHX59SPYmrUygLMI9RdD69tEwyVeTi0F9t7v3H63xUXPuxDtksoYj1HWPDcSXSDCBfbIPhglKx9KPbVjH3HWCaB8o5Q==
alipay.alipayPublicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjhEnnlaYNWqorITiX0u8OVoS0ef0Qv1g1SPlGrds0b2Bt+0PsnvkhG6m0NGv3MBiUVBshow06whhNoGV0TMbloRFa68cchMHjUnXvcYzYrFM8pEBkerlS1DJBU65S0WH+xDAkBQXro/OPeoh0uHWjuorW+ccz3cXHuInNlM6hFEyiwY6XscDP5E/98R4HdYmlQfEo3ZyxedthM2qECo6YFJD2FuINUEKc+6HLYIiAfLNhDAyFpBHpUrO2as7Quq+AjYlr4df0I3dSW63Ywj2nZcQLBVytucyL/OViO8JdP5zDG9jJlxjoo79GxQOJAKXsk+PUIkmUikTKigK96Qa0wIDAQAB
alipay.notifyUrl=http://p49dhg.natappfree.cc/v1/usercenter/server/alipay/callback
alipay.serverUrl=https://openapi-sandbox.dl.alipaydev.com/gateway.do